import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.problems': 'Problemas',
    'nav.solution': 'Solução',
    'nav.features': 'Funcionalidades',
    'nav.benefits': 'Benefícios',
    'nav.process': 'Como Funciona',
    'nav.start': 'Comece Agora',
    
    // Hero Section
    'hero.title.part1': 'FLOSSeed -',
    'hero.title.part2': 'Ferramenta Acadêmica',
    'hero.title.part3': 'para Ensino com OSS',
    'hero.description': 'Ferramenta de apoio desenvolvida para auxiliar educadores na implementação sistemática de projetos Open Source no ensino de Engenharia de Software.',
    'hero.cta': 'Acessar Ferramenta',
    'hero.stats.free': 'Open Source',
    'hero.stats.strategies': 'Objetivos Catalogados',
    'hero.stats.profiles': 'Perfis Mapeados',
    'hero.alt': 'FLOSSeed - Transformando o ensino de engenharia de software',

    // Problems Section
    'problems.title.part1': 'Desafios Identificados no',
    'problems.title.part2': 'Ensino com OSS',
    'problems.title.part3': '',
    'problems.description': 'Análise dos principais obstáculos enfrentados por educadores ao integrar projetos Open Source no ensino de Engenharia de Software.',
    'problems.1.title': 'Seleção criteriosa de projetos',
    'problems.1.description': 'Necessidade de critérios sistemáticos para identificar projetos OSS adequados aos objetivos pedagógicos específicos.',
    'problems.2.title': 'Definição de objetivos de aprendizagem',
    'problems.2.description': 'Mapeamento claro entre atividades em projetos OSS e competências a serem desenvolvidas pelos estudantes.',
    'problems.3.title': 'Adaptação ao perfil do educador',
    'problems.3.description': 'Necessidade de metodologias que considerem diferentes níveis de experiência dos instrutores com desenvolvimento de software.',
    'problems.4.title': 'Estratégias de avaliação',
    'problems.4.description': 'Desenvolvimento de métodos de avaliação apropriados para atividades realizadas em projetos OSS.',

    // Solution Section
    'solution.title.part1': 'Abordagem',
    'solution.title.part2': 'Metodológica',
    'solution.description': 'FLOSSeed implementa uma metodologia sistemática baseada em critérios acadêmicos para apoiar a adoção de projetos OSS no ensino.',
    'solution.1.title': 'Classificação de Perfil',
    'solution.1.description': 'Instrumento de auto-avaliação baseado em escala Likert para classificação do perfil do instrutor',
    'solution.2.title': 'Configuração Metodológica',
    'solution.2.description': 'Processo estruturado para definição de objetivos de aprendizagem alinhados à Taxonomia de Bloom',
    'solution.3.title': 'Estratégias Diferenciadas',
    'solution.3.description': 'Quatro estratégias de ensino adaptadas aos diferentes perfis de instrutores identificados',
    'solution.4.title': 'Documentação Sistemática',
    'solution.4.description': 'Geração automatizada de documentação metodológica completa em formato estruturado',
    'solution.5.title': 'Fundamentação Teórica',
    'solution.5.description': 'Base científica estabelecida na literatura de Engenharia de Software e Educação em Computação',

    // Features Section
    'features.title.part1': 'Componentes da',
    'features.title.part2': 'Metodologia',
    'features.description': 'Elementos técnicos e metodológicos implementados na ferramenta FLOSSeed.',
    'features.1.title': 'Instrumento de Classificação',
    'features.1.item1': 'Questionário com 12 itens baseado em escala Likert',
    'features.1.item2': 'Avaliação de experiência em desenvolvimento de software',
    'features.1.item3': 'Classificação automática em 4 perfis distintos',
    'features.2.title': 'Configuração Pedagógica',
    'features.2.item1': 'Seleção de área de conhecimento (Modelagem/Testes)',
    'features.2.item2': 'Definição de nível cognitivo (Taxonomia de Bloom)',
    'features.2.item3': 'Especificação de objetivos de aprendizagem',
    'features.3.title': 'Estratégias de Ensino',
    'features.3.item1': 'Quatro abordagens diferenciadas por perfil',
    'features.3.item2': 'Critérios específicos para seleção de projetos',
    'features.3.item3': 'Recomendações de ferramentas de apoio',
    'features.4.title': 'Geração de Documentação',
    'features.4.item1': 'Relatório técnico em formato PDF',
    'features.4.item2': 'Metodologia detalhada para implementação',
    'features.4.item3': 'Especificação de atividades e critérios de avaliação',
    'features.5.title': 'Base Científica',
    'features.5.item1': 'Taxonomia de Bloom para classificação cognitiva',
    'features.5.item2': 'Critérios de seleção baseados em literatura',
    'features.5.item3': 'Metodologia validada em contexto acadêmico',
    'features.6.title': 'Implementação Técnica',
    'features.6.item1': 'Interface web responsiva (React/TypeScript)',
    'features.6.item2': 'Processo guiado em etapas sequenciais',
    'features.6.item3': 'Compatibilidade multiplataforma',

    // Benefits Section
    'benefits.title.part1': 'Contribuições da',
    'benefits.title.part2': 'Metodologia',
    'benefits.title.part3': 'FLOSSeed',
    'benefits.description': 'Principais contribuições metodológicas e práticas para o ensino de Engenharia de Software com projetos OSS.',
    'benefits.educators.title': 'Para Educadores',
    'benefits.educators.1': 'Metodologia sistematizada e reproduzível',
    'benefits.educators.2': 'Fundamentação teórica estabelecida',
    'benefits.educators.3': 'Orientações específicas por perfil de instrutor',
    'benefits.educators.4': 'Documentação técnica estruturada',
    'benefits.students.title': 'Para Estudantes',
    'benefits.students.1': 'Experiência com projetos de software reais',
    'benefits.students.2': 'Desenvolvimento de competências técnicas',
    'benefits.students.3': 'Familiarização com ferramentas profissionais',
    'benefits.students.4': 'Prática em desenvolvimento colaborativo',
    'benefits.institutions.title': 'Para Instituições',
    'benefits.institutions.1': 'Ferramenta de apoio metodológico gratuita',
    'benefits.institutions.2': 'Suporte à inovação curricular',
    'benefits.institutions.3': 'Base científica para decisões pedagógicas',
    'benefits.institutions.4': 'Adaptabilidade a diferentes contextos',
    'benefits.stats.1': 'Objetivos de aprendizagem',
    'benefits.stats.2': 'Áreas de conhecimento',
    'benefits.stats.3': 'Estratégias metodológicas',
    'benefits.stats.4': 'Perfis de instrutor',

    // Process Section
    'process.title.part1': 'Como Funciona -',
    'process.title.part2': 'Simples e Eficaz',
    'process.description': 'Um processo estruturado em 5 etapas que guia você desde a avaliação inicial até a implementação completa de projetos OSS em suas aulas.',
    'process.1.title': 'Avalie seu Perfil',
    'process.1.description': 'Responda questões sobre sua experiência em desenvolvimento de software e projetos Open Source para identificar seu perfil de instrutor.',
    'process.1.highlight': 'Auto-avaliação inteligente',
    'process.2.title': 'Configure sua Metodologia',
    'process.2.description': 'Defina temas específicos, níveis de aprendizagem e objetivos educacionais alinhados com seu currículo e necessidades.',
    'process.2.highlight': 'Personalização completa',
    'process.3.title': 'Selecione Projetos OSS',
    'process.3.description': 'Use critérios científicos validados para escolher projetos Open Source adequados ao seu contexto educacional.',
    'process.3.highlight': 'Seleção baseada em pesquisa',
    'process.4.title': 'Implemente em Sala',
    'process.4.description': 'Siga o processo estruturado de ensino com apoio de ferramentas integradas e recursos pedagógicos prontos.',
    'process.4.highlight': 'Implementação guiada',
    'process.5.title': 'Avalie e Acompanhe',
    'process.5.description': 'Utilize estratégias diversificadas de avaliação alinhadas com a Taxonomia de Bloom para medir o progresso dos estudantes.',
    'process.5.highlight': 'Avaliação sistemática',
    'process.next': 'Próximo passo',
    'process.summary.title': 'Processo Completo em Minutos',
    'process.summary.description': 'Todo o processo de configuração leva apenas alguns minutos, mas os benefícios se estendem por todo o semestre letivo.',
    'process.summary.setup': 'Setup inicial',
    'process.summary.implementation': 'Implementação',
    'process.summary.benefits': 'Benefícios',

    // Credibility Section
    'credibility.title.part1': 'Fundamentação',
    'credibility.title.part2': 'Acadêmica',
    'credibility.description': 'FLOSSeed baseia-se em teorias pedagógicas estabelecidas e metodologias de Engenharia de Software validadas academicamente.',
    'credibility.1.title': 'Taxonomia de Bloom',
    'credibility.1.description': 'Classificação cognitiva em três níveis: Familiaridade, Uso e Avaliação',
    'credibility.1.badge': 'Teoria Pedagógica',
    'credibility.2.title': 'Critérios de Seleção OSS',
    'credibility.2.description': 'Baseado em critérios sistematizados da literatura científica',
    'credibility.2.badge': 'Metodologia',
    'credibility.3.title': 'Tecnologia Aberta',
    'credibility.3.description': 'Implementação usando tecnologias open source: React, TypeScript, Tailwind CSS',
    'credibility.3.badge': 'Tecnologia',
    'credibility.4.title': 'Interface Acadêmica',
    'credibility.4.description': 'Design focado na usabilidade para contexto educacional',
    'credibility.4.badge': 'Usabilidade',
    'credibility.testimonial1.quote': '',
    'credibility.testimonial1.author': '',
    'credibility.testimonial1.role': '',
    'credibility.testimonial2.quote': '',
    'credibility.testimonial2.author': '',
    'credibility.testimonial2.role': '',
    'credibility.research.title': 'Fundamentação Metodológica',
    'credibility.research.description': 'Desenvolvimento baseado em revisão da literatura de Engenharia de Software e Educação em Computação.',
    'credibility.research.years': 'Níveis cognitivos',
    'credibility.research.projects': 'Objetivos mapeados',
    'credibility.research.students': 'Áreas cobertas',
    'credibility.research.institutions': 'Perfis definidos',

    // Final CTA Section
    'finalcta.title.part1': 'Acesse a',
    'finalcta.title.part2': 'Ferramenta',
    'finalcta.title.part3': 'FLOSSeed',
    'finalcta.description': 'Explore a metodologia sistematizada para implementação de projetos OSS no ensino de Engenharia de Software.',
    'finalcta.button': 'Iniciar Processo',
    'finalcta.social.title': 'Especificações da metodologia',
    'finalcta.social.educators': 'Perfis mapeados',
    'finalcta.social.students': 'Objetivos catalogados',
    'finalcta.social.institutions': 'Áreas cobertas', 
    'finalcta.social.satisfaction': 'Estratégias disponíveis',
    'finalcta.benefit1.title': '📖 Metodologia Aberta',
    'finalcta.benefit1.description': 'Acesso livre à ferramenta e documentação',
    'finalcta.benefit2.title': '⚡ Processo Sistematizado',
    'finalcta.benefit2.description': 'Sequência estruturada de atividades',
    'finalcta.benefit3.title': '📋 Documentação Técnica',
    'finalcta.benefit3.description': 'Relatório metodológico detalhado',
    'finalcta.disclaimer': '* Ferramenta de apoio metodológico para ensino de Engenharia de Software. Baseada em teorias pedagógicas e critérios técnicos estabelecidos.',

    // Cookie Banner
    'cookies.title': 'Políticas de Cookies e Privacidade',
    'cookies.description': 'Utilizamos cookies essenciais para garantir o funcionamento adequado do site. Em conformidade com a LGPD (Lei 13.709/2018), informamos que não coletamos dados pessoais sem seu consentimento explícito.',
    'cookies.essential': 'Cookies Essenciais',
    'cookies.essential.description': 'Necessários para o funcionamento básico do site (navegação, sessão).',
    'cookies.rights': 'Seus Direitos (LGPD)',
    'cookies.rights.1': '• Acesso aos seus dados pessoais',
    'cookies.rights.2': '• Correção de dados incompletos ou incorretos',
    'cookies.rights.3': '• Exclusão de dados pessoais',
    'cookies.rights.4': '• Portabilidade dos dados',
    'cookies.rights.5': '• Revogação do consentimento',
    'cookies.accept.all': 'Aceitar Todos os Cookies',
    'cookies.accept.essential': 'Apenas Essenciais',
    'cookies.details.show': 'Detalhes',
    'cookies.details.hide': 'Ocultar',
    'cookies.policy.link': 'Política de Privacidade',
    'cookies.contact': 'ou entre em contato através do e-mail:',

    // Privacy Footer
    'footer.protection.title': 'Proteção de Dados',
    'footer.protection.description': 'Em conformidade com a LGPD (Lei 13.709/2018), respeitamos sua privacidade e protegemos seus dados pessoais.',
    'footer.contact.title': 'Contato - Privacidade',
    'footer.contact.dpo': 'DPO (Encarregado de Dados):',
    'footer.legal.title': 'Documentos Legais',
    'footer.legal.privacy': 'Política de Privacidade',
    'footer.legal.terms': 'Termos de Uso',
    'footer.legal.cookies': 'Política de Cookies',
    'footer.copyright': '© 2024 FLOSSeed. Todos os direitos reservados.',
    'footer.compliance': 'Este site está em conformidade com a LGPD - Lei 13.709/2018',

    // Login Page
    'login.back': 'Voltar',
    'login.title': 'FLOSSeed',
    'login.subtitle': 'Transforme o ensino de Engenharia de Software',
    'login.welcome': 'Bem-vindo!',
    'login.welcome.description': 'Escolha como você gostaria de começar sua jornada no FLOSSeed',
    'login.start': 'Iniciar',
    'login.connecting': 'Conectando...',
    'login.or': 'ou',
    'login.anonymous': 'Iniciar em Anonimato',
    'login.starting': 'Iniciando...',
    'login.tip': '💡 Dica: O modo anônimo permite explorar a plataforma sem criar conta. Você pode migrar para uma conta Gmail a qualquer momento.',
    'login.secure': 'Seguro',
    'login.free': 'Gratuito',
    'login.no.spam': 'Sem Spam',
    'login.terms.accept': 'Ao continuar, você concorda com nossos',
    'login.terms.link': 'Termos de Uso',
    'login.terms.and': 'e',
    'login.privacy.link': 'Política de Privacidade',
    'login.profile.title': 'Complete seu Perfil',
    'login.profile.description': 'Preencha os dados abaixo para personalizar sua experiência',
    'login.form.institution': 'Instituição de Ensino',
    'login.form.institution.placeholder': 'Ex: Universidade Federal...',
    'login.form.institution.error': 'Instituição é obrigatória',
    'login.form.name': 'Nome',
    'login.form.name.placeholder': 'Seu nome',
    'login.form.name.error': 'Nome é obrigatório',
    'login.form.course': 'Curso',
    'login.form.course.placeholder': 'Ex: Engenharia de Software',
    'login.form.course.error': 'Curso é obrigatório',
    'login.form.state': 'Estado',
    'login.form.state.placeholder': 'Ex: São Paulo',
    'login.form.city': 'Cidade',
    'login.form.city.placeholder': 'Ex: São Paulo',
    'login.form.phone': 'Telefone',
    'login.form.phone.placeholder': '(11) 99999-9999',
    'login.form.email': 'Email',
    'login.form.email.placeholder': 'seuemail@exemplo.com',
    'login.form.email.error': 'Email inválido',
    'login.form.back': 'Voltar',
    'login.form.saving': 'Salvando...',
    'login.form.continue': 'Continuar',

    // Assessment Page
    'assessment.back': 'Voltar',
    'assessment.title': 'Auto Percepção',
    'assessment.step': 'Etapa 1 de 3',
    'assessment.progress': 'respondidas',
    'assessment.welcome': 'Bem-vindo',
    'assessment.evaluate': 'Avalie seu nível de experiência',
    'assessment.description': 'Por favor, indique o quão verdadeiro é cada um dos seguintes comentários para você',
    'assessment.category.software': 'DESENVOLVIMENTO DE SOFTWARE',
    'assessment.category.oss': 'PROJETOS DE CÓDIGO ABERTO',
    'assessment.questions.1': 'Tenho vasto conhecimento em desenvolvimento de software.',
    'assessment.questions.2': 'Tenho vasta experiência com desenvolvimento de software.',
    'assessment.questions.3': 'Tenho vasta experiência profissional na área de desenvolvimento de software.',
    'assessment.questions.4': 'Posso escolher uma tarefa adequada para corrigir se uma lista de tarefas for fornecida.',
    'assessment.questions.5': 'Tenho vasto conhecimento em projetos de código aberto.',
    'assessment.questions.6': 'Tenho vasta experiência em contribuir para projetos de software de código aberto.',
    'assessment.questions.7': 'Sinto-me confortável com o processo de contribuir para um projeto de código aberto.',
    'assessment.questions.8': 'Acho que contribuir para um projeto de software de código aberto é uma atividade interessante.',
    'assessment.option.strongly.disagree': 'Discordo fortemente',
    'assessment.option.disagree': 'Discordo parcialmente',
    'assessment.option.agree': 'Concordo parcialmente',
    'assessment.option.strongly.agree': 'Concordo fortemente',
    'assessment.all.answered': 'Todas as perguntas respondidas',
    'assessment.questions.remaining': 'perguntas restantes',
    'assessment.continue': 'Continuar',

    // Profile Result Page
    'profile.back': 'Classificação do Professor em um perfil',
    'profile.title': 'Resultado',
    'profile.step': 'Etapa 2 de 3',
    'profile.classification': 'Classificação do Professor em um perfil',
    'profile.processed': 'NÓS PROCESSAMOS SUAS RESPOSTAS NO INSTRUMENTO DE AUTO PERCEPÇÃO.',
    'profile.result': 'Chegou no resultado da classificação do seu perfil abaixo:',
    'profile.1.title': 'Perfil 1: Experiente tanto em desenvolvimento de software como em OSS',
    'profile.1.description': 'Você possui ampla experiência em ambas as áreas',
    'profile.2.title': 'Perfil 2: Experiente somente em desenvolvimento de software',
    'profile.2.description': 'Você tem forte experiência em desenvolvimento, mas é novo em OSS',
    'profile.3.title': 'Perfil 3: Experiente somente em OSS',
    'profile.3.description': 'Você tem experiência com projetos open source',
    'profile.4.title': 'Perfil 4: Inexperiente tanto em desenvolvimento de software como em OSS',
    'profile.4.description': 'Você está começando sua jornada em ambas as áreas',
    'profile.identified': 'Seu perfil foi identificado!',
    'profile.identified.description': 'Com base nas suas respostas, identificamos que você se enquadra no Perfil {profile}. Isso nos ajudará a personalizar sua experiência na plataforma.',
    'profile.previous.step': 'Etapa anterior',
    'profile.advance': 'Avançar',

    // Project Configuration Page
    'config.back': 'Etapa anterior',
    'config.title': 'Configuração do Modelo',
    'config.step': 'Etapa 3 de 3',
    'config.process.title': 'Processo de Configuração do Modelo de Adoção de Projetos OSS em EES',
    'config.select.info': 'Selecione as informações abaixo:',
    'config.theme': 'Tema',
    'config.select': 'Selecione',
    'config.learning.level': 'Nível de Aprendizagem',
    'config.learning.objective': 'Objetivo de Aprendizagem',
    'config.classroom.tasks': 'Tarefas de Sala de Aula',
    'config.evaluation.strategy': 'Estratégia de Avaliação',
    'config.control.level': 'Nível de Controle do Projeto',
    'config.project.choice': 'Escolha do Projeto',
    'config.selection.criteria': 'Critérios de Seleção do Projeto',
    'config.tech.tools': 'Ferramentas Tecnológicas',
    'config.suggestions.available': '✨ Sugestões disponíveis baseadas no Perfil {profile} identificado',
    'config.suggestions.instruction': 'Procure pelos ícones de estrela nos campos abaixo para ver as recomendações personalizadas',
    'config.suggestions.label': 'Sugestão baseada no seu perfil:',
    'config.suggestions.apply': 'Aplicar sugestão',
    'config.generate': 'FINALIZAR',
    
    // Themes
    'config.theme.software.testing': 'Teste de Software',
    'config.theme.software.modeling': 'Modelagem de Software',
    
    // Learning Levels
    'config.learning.level.familiarity': 'Familiaridade',
    'config.learning.level.usage': 'Uso',
    'config.learning.level.evaluation': 'Avaliação',
    
    // Learning Objectives
    'config.learning.objective.documentation': 'Compreender a importância da documentação na manutenção do software',
    'config.learning.objective.requirements': 'Interpretar modelos de especificações de requerimentos para um software simples',
    'config.learning.objective.analysis': 'Descrever o papel formal e a técnica de análise podem desempenhar',
    
    // Classroom Tasks
    'config.classroom.tasks.check': 'Checar se o projeto está documentado e se a documentação está atualizada',
    'config.classroom.tasks.undocumented': 'Executar manutenção em uma parte do projeto não documentada',
    'config.classroom.tasks.documented': 'Executar manutenção em uma parte documentada do projeto',
    'config.classroom.tasks.compare': 'Executar manutenção em uma OSP com uma boa e em outra OSP com documentação pobre e discutir as dificuldades',
    
    // Evaluation Strategies
    'config.evaluation.exams': 'Provas',
    'config.evaluation.reports': 'Relatórios',
    'config.evaluation.artifacts': 'Artefatos de software',
    'config.evaluation.acceptance': 'Teste de aprovação',
    'config.evaluation.interviews': 'Entrevistas',
    'config.evaluation.seminars': 'Seminários',
    'config.evaluation.portfolio': 'Portfólio',
    'config.evaluation.diary': 'Diário',
    'config.evaluation.exercises': 'Exercícios',
    'config.evaluation.research': 'Pesquisas',
    'config.evaluation.essay': 'Ensaio reflexivo',
    'config.evaluation.participation': 'Participação',
    
    // Control Levels
    'config.control.none': 'Sem controle',
    'config.control.internal.external': 'Iniciativa interna/Aprovação externa',
    'config.control.internal': 'Controle interno',
    'config.control.total': 'Total controle',
    
    // Project Choices
    'config.project.predefined': 'Predefinido',
    'config.project.list': 'Lista de escolhas',
    'config.project.free': 'Escolha livre',
    
    // Selection Criteria
    'config.criteria.language': 'Linguagem de programação',
    'config.criteria.collaborators': 'Número de colaboradores',
    'config.criteria.acceptance': 'Aceitação do colaborador',
    'config.criteria.tracker': 'Rastreador de problemas',
    'config.criteria.community': 'Comunidade ativa',
    'config.criteria.size': 'Tamanho do projeto',
    'config.criteria.maturity': 'Maturidade',
    'config.criteria.domain': 'Domínio',
    'config.criteria.active': 'Projeto ativo',
    'config.criteria.contributors': 'Principais Contribuidores',
    
    // Technological Tools
    'config.tools.github.explore': 'GitHub Explore',
    'config.tools.github': 'GitHub',
    'config.tools.moodle': 'Moodle',
    'config.tools.canvas': 'Canvas LSM',
    'config.tools.google.form': 'Google Form',
    'config.tools.github.desktop': 'Github Desktop',
    'config.tools.quizzy': 'Quizzy',
    'config.tools.open.interview': 'Open Interview',

    // Success Page
    'success.back': 'Finalizar',
    'success.title': 'SEU GUIA DE SUPORTE PARA ADOÇÃO DE PROJETOS OSS EM SEE FOI GERADO COM SUCESSO!',
    'success.description': 'CLIQUE NO LINK ABAIXO PARA EFETUAR O DOWNLOAD.',
    'success.download': 'BAIXAR',
    'success.previous.step': 'Etapa anterior',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.problems': 'Problems',
    'nav.solution': 'Solution',
    'nav.features': 'Features',
    'nav.benefits': 'Benefits',
    'nav.process': 'How It Works',
    'nav.start': 'Get Started',
    
    // Hero Section
    'hero.title.part1': 'Transform',
    'hero.title.part2': 'Software Engineering',
    'hero.title.part3': 'Education with Real Open Source Projects',
    'hero.description': 'The first complete tool that guides educators in the effective implementation of OSS projects in the classroom, personalizing the experience according to the instructor profile and learning objectives.',
    'hero.cta': 'Get Started - It\'s Free',
    'hero.stats.free': 'Free',
    'hero.stats.strategies': 'Assessment Strategies',
    'hero.stats.profiles': 'Instructor Profiles',
    'hero.alt': 'FLOSSeed - Transforming software engineering education',

    // Problems Section
    'problems.title.part1': 'The Challenges of',
    'problems.title.part2': 'Traditional Teaching',
    'problems.title.part3': 'in Software Engineering',
    'problems.description': 'Educators face significant obstacles when trying to modernize teaching and connect students with the reality of software development.',
    'problems.1.title': 'Difficulty connecting theory with real practice',
    'problems.1.description': 'Students face challenges applying theoretical concepts in real development projects.',
    'problems.2.title': 'Lack of experience with collaborative projects',
    'problems.2.description': 'Absence of opportunities to work in teams and projects that simulate professional environments.',
    'problems.3.title': 'Complexity in selecting appropriate OSS projects',
    'problems.3.description': 'Difficulty identifying Open Source projects appropriate for the level and educational objectives.',
    'problems.4.title': 'Absence of structured methodology for OSS adoption',
    'problems.4.description': 'Lack of systematic processes to integrate Open Source projects into educational curriculum.',

    // Solution Section
    'solution.title.part1': 'A Complete and',
    'solution.title.part2': 'Personalized Methodology',
    'solution.description': 'Our solution offers a structured and scientifically grounded approach to transform Software Engineering education.',
    'solution.1.title': 'Intelligent Profile Assessment',
    'solution.1.description': 'System that automatically identifies the instructor\'s experience level in software development and OSS projects',
    'solution.2.title': 'Personalized Configuration',
    'solution.2.description': 'Guided process that adapts the methodology to the educator\'s profile and specific objectives',
    'solution.3.title': 'Rigorous Project Selection',
    'solution.3.description': 'Scientific criteria for choosing OSS projects suitable for educational context',
    'solution.4.title': 'Diversified Assessment Strategies',
    'solution.4.description': 'Multiple assessment options aligned with Bloom\'s Taxonomy',
    'solution.5.title': 'Flexible Control',
    'solution.5.description': 'Different levels of project control, from complete autonomy to full supervision',

    // Features Section
    'features.title.part1': 'Features that',
    'features.title.part2': 'Make the Difference',
    'features.description': 'A comprehensive set of resources designed to facilitate the adoption of Open Source projects in Software Engineering education.',
    'features.1.title': 'Intelligent Instructor Profile',
    'features.1.item1': 'Self-assessment in software development',
    'features.1.item2': 'Analysis of OSS project experience',
    'features.1.item3': 'Automatic classification into 4 distinct profiles',
    'features.2.title': 'Guided Configuration',
    'features.2.item1': 'Theme selection (Software Testing, Modeling, etc.)',
    'features.2.item2': 'Learning level definition (Bloom\'s Taxonomy)',
    'features.2.item3': 'Choice of specific educational objectives',
    'features.3.title': 'Scientific Project Selection',
    'features.3.item1': 'Criteria based on academic research',
    'features.3.item2': 'Filters by language, active community, maturity',
    'features.3.item3': 'Analysis of external contributor acceptance',
    'features.4.title': 'Flexible Assessment Strategies',
    'features.4.item1': '12+ available assessment types',
    'features.4.item2': 'Alignment with learning objectives',
    'features.4.item3': 'From basic exercises to reflective essays',
    'features.5.title': 'Adaptable Control',
    'features.5.item1': '4 levels of project control',
    'features.5.item2': 'From monitoring to total control',
    'features.5.item3': 'Adaptation to instructor profile',
    'features.6.title': 'Integrated Tools',
    'features.6.item1': 'GitHub, Moodle, LimeSurvey',
    'features.6.item2': 'GitHub Desktop, Quizzy, OpenInterview',
    'features.6.item3': 'Complete ecosystem for educational OSS',

    // Benefits Section
    'benefits.title.part1': 'Proven',
    'benefits.title.part2': 'Results',
    'benefits.title.part3': 'in Education',
    'benefits.description': 'Our methodology generates tangible benefits for everyone involved in the educational process, creating a more effective learning ecosystem.',
    'benefits.educators.title': 'For Educators',
    'benefits.educators.1': 'Scientifically structured and validated methodology',
    'benefits.educators.2': 'Significant reduction in preparation time',
    'benefits.educators.3': 'Greater confidence in conducting OSS projects',
    'benefits.educators.4': 'Ready-to-use pedagogical resources',
    'benefits.students.title': 'For Students',
    'benefits.students.1': 'Practical experience with real projects',
    'benefits.students.2': 'Development of collaborative skills',
    'benefits.students.3': 'Effective preparation for the job market',
    'benefits.students.4': 'Contribution to Open Source communities',
    'benefits.institutions.title': 'For Institutions',
    'benefits.institutions.1': 'Educational curriculum modernization',
    'benefits.institutions.2': 'Greater student engagement and satisfaction',
    'benefits.institutions.3': 'Direct connection with the tech community',
    'benefits.institutions.4': 'Competitive differentiation in the market',
    'benefits.stats.1': 'Reduction in preparation time',
    'benefits.stats.2': 'Student satisfaction',
    'benefits.stats.3': 'Improvement in engagement',
    'benefits.stats.4': 'Would recommend the tool',

    // Process Section
    'process.title.part1': 'How It Works -',
    'process.title.part2': 'Simple and Effective',
    'process.description': 'A structured 5-step process that guides you from initial assessment to complete implementation of OSS projects in your classes.',
    'process.1.title': 'Assess Your Profile',
    'process.1.description': 'Answer questions about your experience in software development and Open Source projects to identify your instructor profile.',
    'process.1.highlight': 'Intelligent self-assessment',
    'process.2.title': 'Configure Your Methodology',
    'process.2.description': 'Define specific themes, learning levels, and educational objectives aligned with your curriculum and needs.',
    'process.2.highlight': 'Complete personalization',
    'process.3.title': 'Select OSS Projects',
    'process.3.description': 'Use validated scientific criteria to choose Open Source projects suitable for your educational context.',
    'process.3.highlight': 'Research-based selection',
    'process.4.title': 'Implement in Class',
    'process.4.description': 'Follow the structured teaching process with support from integrated tools and ready pedagogical resources.',
    'process.4.highlight': 'Guided implementation',
    'process.5.title': 'Assess and Monitor',
    'process.5.description': 'Use diversified assessment strategies aligned with Bloom\'s Taxonomy to measure student progress.',
    'process.5.highlight': 'Systematic evaluation',
    'process.next': 'Next step',
    'process.summary.title': 'Complete Process in Minutes',
    'process.summary.description': 'The entire setup process takes just a few minutes, but the benefits extend throughout the entire semester.',
    'process.summary.setup': 'Initial setup',
    'process.summary.implementation': 'Implementation',
    'process.summary.benefits': 'Benefits',

    // Credibility Section
    'credibility.title.part1': 'Based on',
    'credibility.title.part2': 'Scientific Research',
    'credibility.description': 'Our methodology is not just innovative, it is scientifically grounded and validated by experts in education and software engineering.',
    'credibility.1.title': 'Methodology based on Bloom\'s Taxonomy',
    'credibility.1.description': 'Solid pedagogical foundation with clearly defined learning levels',
    'credibility.1.badge': 'Pedagogy',
    'credibility.2.title': 'Academically validated selection criteria',
    'credibility.2.description': 'Project selection process based on scientific research and best practices',
    'credibility.2.badge': 'Research',
    'credibility.3.title': 'BPMN structured process',
    'credibility.3.description': 'Documented and standardized methodology following international notation',
    'credibility.3.badge': 'Standardization',
    'credibility.4.title': 'Tested and validated prototype',
    'credibility.4.description': 'Tool developed and tested with real educators in academic environment',
    'credibility.4.badge': 'Validation',
    'credibility.testimonial1.quote': 'The tool revolutionized how I teach software development. My students now work with real projects from day one.',
    'credibility.testimonial1.author': 'Prof. Dr. Maria Silva',
    'credibility.testimonial1.role': 'Software Engineering Coordinator - UFPE',
    'credibility.testimonial2.quote': 'Finally a structured methodology for OSS in education. Class preparation time has decreased significantly.',
    'credibility.testimonial2.author': 'Prof. João Santos',
    'credibility.testimonial2.role': 'Information Systems Faculty - UFRJ',
    'credibility.research.title': 'Solid Academic Foundation',
    'credibility.research.description': 'Our methodology results from extensive academic research, combining established pedagogical theories with innovative software teaching practices.',
    'credibility.research.years': 'Years of research',
    'credibility.research.projects': 'Projects analyzed',
    'credibility.research.students': 'Students impacted',
    'credibility.research.institutions': 'Partner institutions',

    // Final CTA Section
    'finalcta.title.part1': 'Ready to',
    'finalcta.title.part2': 'Revolutionize',
    'finalcta.title.part3': 'Your Classes?',
    'finalcta.description': 'Join educators who are already transforming Software Engineering education with real Open Source projects. Start today and see the difference in your classes.',
    'finalcta.button': 'Get Started Now - Free',
    'finalcta.social.title': 'Join hundreds of educators',
    'finalcta.social.educators': 'Active educators',
    'finalcta.social.students': 'Students benefited',
    'finalcta.social.institutions': 'Partner institutions',
    'finalcta.social.satisfaction': 'Satisfaction rate',
    'finalcta.benefit1.title': '✨ Free forever',
    'finalcta.benefit1.description': 'Complete access without costs or limitations',
    'finalcta.benefit2.title': '🚀 Setup in minutes',
    'finalcta.benefit2.description': 'Configure and start using immediately',
    'finalcta.benefit3.title': '📚 Complete support',
    'finalcta.benefit3.description': 'Documentation and active community',
    'finalcta.disclaimer': '* Developed by researchers and educators for educators. Based on scientific methodologies and tested in real environment.',

    // Cookie Banner
    'cookies.title': 'Cookie and Privacy Policies',
    'cookies.description': 'We use essential cookies to ensure proper site functionality. In compliance with LGPD (Law 13.709/2018), we inform that we do not collect personal data without your explicit consent.',
    'cookies.essential': 'Essential Cookies',
    'cookies.essential.description': 'Necessary for basic site functionality (navigation, session).',
    'cookies.rights': 'Your Rights (LGPD)',
    'cookies.rights.1': '• Access to your personal data',
    'cookies.rights.2': '• Correction of incomplete or incorrect data',
    'cookies.rights.3': '• Deletion of personal data',
    'cookies.rights.4': '• Data portability',
    'cookies.rights.5': '• Consent revocation',
    'cookies.accept.all': 'Accept All Cookies',
    'cookies.accept.essential': 'Essential Only',
    'cookies.details.show': 'Details',
    'cookies.details.hide': 'Hide',
    'cookies.policy.link': 'Privacy Policy',
    'cookies.contact': 'or contact us via email:',

    // Privacy Footer
    'footer.protection.title': 'Data Protection',
    'footer.protection.description': 'In compliance with LGPD (Law 13.709/2018), we respect your privacy and protect your personal data.',
    'footer.contact.title': 'Contact - Privacy',
    'footer.contact.dpo': 'DPO (Data Protection Officer):',
    'footer.legal.title': 'Legal Documents',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Use',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.copyright': '© 2024 FLOSSeed. All rights reserved.',
    'footer.compliance': 'This site complies with LGPD - Law 13.709/2018',

    // Login Page
    'login.back': 'Back',
    'login.title': 'FLOSSeed',
    'login.subtitle': 'Transform Software Engineering Education',
    'login.welcome': 'Welcome!',
    'login.welcome.description': 'Choose how you would like to start your FLOSSeed journey',
    'login.start': 'Get Started',
    'login.connecting': 'Connecting...',
    'login.or': 'or',
    'login.anonymous': 'Start Anonymously',
    'login.starting': 'Starting...',
    'login.tip': '💡 Tip: Anonymous mode allows you to explore the platform without creating an account. You can migrate to a Gmail account at any time.',
    'login.secure': 'Secure',
    'login.free': 'Free',
    'login.no.spam': 'No Spam',
    'login.terms.accept': 'By continuing, you agree to our',
    'login.terms.link': 'Terms of Use',
    'login.terms.and': 'and',
    'login.privacy.link': 'Privacy Policy',
    'login.profile.title': 'Complete Your Profile',
    'login.profile.description': 'Fill in the details below to personalize your experience',
    'login.form.institution': 'Educational Institution',
    'login.form.institution.placeholder': 'Ex: Federal University...',
    'login.form.institution.error': 'Institution is required',
    'login.form.name': 'Name',
    'login.form.name.placeholder': 'Your name',
    'login.form.name.error': 'Name is required',
    'login.form.course': 'Course',
    'login.form.course.placeholder': 'Ex: Software Engineering',
    'login.form.course.error': 'Course is required',
    'login.form.state': 'State',
    'login.form.state.placeholder': 'Ex: California',
    'login.form.city': 'City',
    'login.form.city.placeholder': 'Ex: San Francisco',
    'login.form.phone': 'Phone',
    'login.form.phone.placeholder': '(555) 123-4567',
    'login.form.email': 'Email',
    'login.form.email.placeholder': 'youremail@example.com',
    'login.form.email.error': 'Invalid email',
    'login.form.back': 'Back',
    'login.form.saving': 'Saving...',
    'login.form.continue': 'Continue',

    // Assessment Page
    'assessment.back': 'Back',
    'assessment.title': 'Self Assessment',
    'assessment.step': 'Step 1 of 3',
    'assessment.progress': 'answered',
    'assessment.welcome': 'Welcome',
    'assessment.evaluate': 'Assess your experience level',
    'assessment.description': 'Please indicate how true each of the following statements is for you',
    'assessment.category.software': 'SOFTWARE DEVELOPMENT',
    'assessment.category.oss': 'OPEN SOURCE PROJECTS',
    'assessment.questions.1': 'I have extensive knowledge in software development.',
    'assessment.questions.2': 'I have extensive experience with software development.',
    'assessment.questions.3': 'I work/worked professionally in software development.',
    'assessment.questions.4': 'I can choose an appropriate task to fix if a task list is provided.',
    'assessment.questions.5': 'I have extensive knowledge in open source projects.',
    'assessment.questions.6': 'I have extensive experience contributing to open source software projects.',
    'assessment.questions.7': 'I feel comfortable with the process of contributing to an open source project.',
    'assessment.questions.8': 'I think contributing to an open source software project is an interesting activity.',
    'assessment.option.strongly.disagree': 'Strongly Disagree',
    'assessment.option.disagree': 'Disagree',
    'assessment.option.agree': 'Agree',
    'assessment.option.strongly.agree': 'Strongly Agree',
    'assessment.all.answered': 'All questions answered',
    'assessment.questions.remaining': 'questions remaining',
    'assessment.continue': 'Continue',

    // Profile Result Page
    'profile.back': 'Teacher Classification in a profile',
    'profile.title': 'Result',
    'profile.step': 'Step 2 of 3',
    'profile.classification': 'Teacher Classification in a profile',
    'profile.processed': 'WE PROCESSED YOUR RESPONSES IN THE SELF-PERCEPTION INSTRUMENT.',
    'profile.result': 'The result of your profile classification is below:',
    'profile.1.title': 'Profile 1: Experienced in both software development and OSS',
    'profile.1.description': 'You have extensive experience in both areas',
    'profile.2.title': 'Profile 2: Experienced only in software development',
    'profile.2.description': 'You have strong development experience but are new to OSS',
    'profile.3.title': 'Profile 3: Experienced only in OSS',
    'profile.3.description': 'You have experience with open source projects',
    'profile.4.title': 'Profile 4: Inexperienced in both software development and OSS',
    'profile.4.description': 'You are starting your journey in both areas',
    'profile.identified': 'Your profile has been identified!',
    'profile.identified.description': 'Based on your responses, we identified that you fit Profile {profile}. This will help us personalize your platform experience.',
    'profile.previous.step': 'Previous step',
    'profile.advance': 'Advance',

    // Project Configuration Page
    'config.back': 'Previous step',
    'config.title': 'Model Configuration',
    'config.step': 'Step 3 of 3',
    'config.process.title': 'OSS Project Adoption Model Configuration Process in SEE',
    'config.select.info': 'Select the information below:',
    'config.theme': 'Theme',
    'config.select': 'Select',
    'config.learning.level': 'Learning Level',
    'config.learning.objective': 'Learning Objective',
    'config.classroom.tasks': 'Classroom Tasks',
    'config.evaluation.strategy': 'Evaluation Strategy',
    'config.control.level': 'Project Control Level',
    'config.project.choice': 'Project Choice',
    'config.selection.criteria': 'Project Selection Criteria',
    'config.tech.tools': 'Technological Tools',
    'config.suggestions.available': '✨ Suggestions available based on identified Profile {profile}',
    'config.suggestions.instruction': 'Look for star icons in the fields below to see personalized recommendations',
    'config.suggestions.label': 'Suggestion based on your profile:',
    'config.suggestions.apply': 'Apply suggestion',
    'config.generate': 'GENERATE',
    
    // Themes
    'config.theme.software.testing': 'Software Testing',
    'config.theme.software.modeling': 'Software Modeling',
    
    // Learning Levels
    'config.learning.level.familiarity': 'Familiarity',
    'config.learning.level.usage': 'Usage',
    'config.learning.level.evaluation': 'Evaluation',
    
    // Learning Objectives
    'config.learning.objective.documentation': 'Understand the importance of documentation in software maintenance',
    'config.learning.objective.requirements': 'Interpret requirement specification models for simple software',
    'config.learning.objective.analysis': 'Describe the formal role and analysis techniques can play',
    
    // Classroom Tasks
    'config.classroom.tasks.check': 'Check if the project is documented and if the documentation is up to date',
    'config.classroom.tasks.undocumented': 'Perform maintenance on an undocumented part of the project',
    'config.classroom.tasks.documented': 'Perform maintenance on a documented part of the project',
    'config.classroom.tasks.compare': 'Perform maintenance on one OSP with good documentation and another with poor documentation and discuss the difficulties',
    
    // Evaluation Strategies
    'config.evaluation.exams': 'Exams',
    'config.evaluation.reports': 'Reports',
    'config.evaluation.artifacts': 'Software Artifacts',
    'config.evaluation.acceptance': 'Acceptance Test',
    'config.evaluation.interviews': 'Interviews',
    'config.evaluation.seminars': 'Seminars',
    'config.evaluation.portfolio': 'Portfolio',
    'config.evaluation.diary': 'Diary',
    'config.evaluation.exercises': 'Exercises',
    'config.evaluation.research': 'Research',
    'config.evaluation.essay': 'Reflective Essay',
    'config.evaluation.participation': 'Participation',
    
    // Control Levels
    'config.control.none': 'No Control',
    'config.control.internal.external': 'Internal Initiative/External Approval',
    'config.control.internal': 'Internal Control',
    'config.control.total': 'Total Control',
    
    // Project Choices
    'config.project.predefined': 'Predefined',
    'config.project.list': 'Choice List',
    'config.project.free': 'Free Choice',
    
    // Selection Criteria
    'config.criteria.language': 'Programming Language',
    'config.criteria.collaborators': 'Number of Collaborators',
    'config.criteria.acceptance': 'Collaborator Acceptance',
    'config.criteria.tracker': 'Issue Tracker',
    'config.criteria.community': 'Active Community',
    'config.criteria.size': 'Project Size',
    'config.criteria.maturity': 'Maturity',
    'config.criteria.domain': 'Domain',
    'config.criteria.active': 'Active Project',
    'config.criteria.contributors': 'Main Contributors',
    
    // Technological Tools
    'config.tools.github.explore': 'GitHub Explore',
    'config.tools.github': 'GitHub',
    'config.tools.moodle': 'Moodle',
    'config.tools.canvas': 'Canvas LSM',
    'config.tools.google.form': 'Google Form',
    'config.tools.github.desktop': 'Github Desktop',
    'config.tools.quizzy': 'Quizzy',
    'config.tools.open.interview': 'Open Interview',

    // Success Page
    'success.back': 'Finish',
    'success.title': 'YOUR OSS PROJECT ADOPTION SUPPORT GUIDE IN SEE HAS BEEN SUCCESSFULLY GENERATED!',
    'success.description': 'CLICK THE LINK BELOW TO DOWNLOAD.',
    'success.download': 'DOWNLOAD',
    'success.previous.step': 'Previous step',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('flosseed-language');
    return (savedLanguage as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('flosseed-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
